name: 01-Buidling Blocks
on:
    workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo " hello world!"
    
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
        - name: successful step
          run: exit 0
        - name: Say Goodbye
          run: echo "Goodbye world!"
        

