name: 06-contexts
on: 
  push:
  workflow_dispatch:

run-name: My custom workflow run name - ${{ runner.os }}

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
    - name: Display Information
      run: |
        echo "Event name ${{ github.event }}"
        echo "Ref: ${{github.ref}}"
        echo "sha: ${{github.sha}}"
        echo "actor: ${{github.actor}}"
        echo "workflow: ${{github.workflow}}"
        echo "run_id: ${{github.run_id}}"
        echo "run_number: ${{github.run_number}}"
        echo "action_ref: ${{github.action_ref}}"
  
    - name: Retrieve Variable
      run: |
        echo " Variable value: ${{ vars.MY_VAR }}"

