name: 07- using expressions

run-name: "07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}


on: 
  push:
  workflow_dispatch:
    inputs: 
      debug:
        type: boolean
        default: false

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if:  inputs.debug 
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref}}"
          echo "sha : ${{ github.sha }}"
          echo "runner OS : ${{ runner.os }}"

      - name: '[debug] Print when Triggered from main'
        if: inputs.debug  &&  github.ref == 'refs/heads/main' 
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "branch: ${{ github.ref}}"
          echo "sha: ${{ github.sha }}"
          echo "Runner OS : ${{ runner.os }}"

      - name: Greeting
        run: echo "Hello, world"

