name: 08 - Using variables
on: push
env:
  WORKFLOW_VAR: 'I am a workflow env'
  OVERWRITTEN: 'I will be overwritten'

jobs:
  echo:
  runs-on: ubuntu-latest
  env:
    JOB_VAR: 'I am a job env var'
    OVERWRITTEN: 'I have beeen overwritten'
  steps: 
    - name: Print Env Variables
      STEP_VAR: 'I am a step env var'
      step_var2: 'I am another step var'

      run: |
        echo " Step env var: ${{ vars.STEP_VAR }}"
        echo " Step env var: ${{ vars.step_var2 }}"

        echo " Step env var: ${{ vars.JOB_VAR }}"
        echo " Step env var: ${{ vars.OVERWRITTEN }}"

        echo " Step env var: ${{ vars.WORKFLOW_VAR }}"
        echo " Step env var: ${{ vars.OVERWRITTEN }}"


