name: 12 - working with outputs
on:
  workflow_dispatch:
    inputs: 
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Set the build status to success or failure"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print "$GITHUB_OUTPUT" path
        run: echo $GITHUB_OUTPUT
      - name: build
        id: build
      
        run: |
            echo "$GITHUB_OUTPUT"   >> "$GITHUB_OUTPUT"
            echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
            echo "Github Output Path: $GITHUB_OUTPUT"



  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy based on build result
  #       run: |
  #         if [ "${{ needs.build.outputs.build-result }}" == "success" ]; then
  #           echo "Deploying application..."
  #         else
  #           echo "Skipping deployment due to build failure."
  #         fi