name: 12 - working with outputs
on:
  workflow_dispatch:
    inputs: 
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Set the build status to success or failure"
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}


    steps:
      - name: Print "$GITHUB_OUTPUT" path
        run: echo $GITHUB_OUTPUT
      - name: build
        id: build
      
        run: |
              echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
              echo "Github Output Path: $GITHUB_OUTPUT"
              echo "---- File contents ----"
              
              echo "ouput1=value1" >> "$GITHUB_OUTPUT"
              echo "ouptut2=value2" >> "$GITHUB_OUTPUT"
              cat "$GITHUB_OUTPUT"
              echo "mistake=true" > "$GITHUB_OUTPUT"
              cat "$GITHUB_OUTPUT"


  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy based on build result
        run: echo "Deploying application..."
      - name: Step with mistake
        run: |
          echo "This step has a mistake"
          echo "ouptut2=value2" >> "$GITHUB_OUTPUT"
          cat "GITHUB_OUTPUT"
