name: My NPM package workflow
on: push

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}- ${{ matrix.node }}
    strategy:
      matrix:
        node: [18, 20, 22]
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}